/**
 * Builds the iCalendar text of a new task or subtask with `@spy4x/time`'s `newTodo`. The caller
 * supplies the `UID` and the clock, so the function is pure; the caller creates the resource with
 * `If-None-Match: *`.
 */

import { serializeIcal } from "@spy4x/time/ical"
import { newTodo, type TodoPatch } from "@spy4x/time/ical-tasks"
import type { Task, TaskDate } from "./types.ts"

/** The `PRODID` this app writes into the tasks it creates. */
export const PRODID = `-//spy4x//caldav-tasks-web//EN`

/** The fields a new task can start with. */
export interface NewTaskFields {
  title: string
  notes?: string
  /** A date, a floating time or a UTC time: a new text has no `VTIMEZONE` for a zoned one. */
  due?: TaskDate
  start?: TaskDate
  /** The iCalendar `PRIORITY`, 0 to 9. */
  priority?: number
  tags?: string[]
}

export interface NewTaskContext {
  /** The new task's `UID`, generated by the caller. */
  uid: string
  now: Date
  /** The `href` of the list the task goes into. Ignored for a subtask: it joins its parent's. */
  listHref: string
  /** Makes the task a subtask of this one. */
  parent?: Task
}

export type CreateResult =
  | { success: true; output: CreateOutput; error: null }
  | { success: false; output: null; error: string }

export interface CreateOutput {
  uid: string
  /** The list the task goes into: the parent's for a subtask. */
  listHref: string
  /** Where to create the resource: the list plus `<uid>.ics`. */
  href: string
  ics: string
}

/** Builds the text for a new task. A subtask carries its parent's `UID` in `RELATED-TO`. */
export function createTask(fields: NewTaskFields, context: NewTaskContext): CreateResult {
  const patch: TodoPatch = { summary: fields.title }
  if (fields.notes) patch.description = fields.notes
  if (fields.due) patch.due = fields.due
  if (fields.start) patch.start = fields.start
  if (fields.priority) patch.priority = fields.priority
  if (fields.tags?.length) patch.categories = fields.tags
  if (context.parent) patch.relatedTo = [{ uid: context.parent.uid, type: `PARENT` }]
  const built = newTodo(patch, { uid: context.uid, now: context.now, prodid: PRODID })
  if (!built.success) return { success: false, output: null, error: built.error.message }
  const listHref = context.parent?.listHref ?? context.listHref
  const href = `${listHref.endsWith(`/`) ? listHref : `${listHref}/`}${context.uid}.ics`
  return {
    success: true,
    output: { uid: context.uid, listHref, href, ics: serializeIcal(built.output) },
    error: null,
  }
}
